# nfl_data.py - Complete 32-Team NFL Schedule with Home/Away Indicators

NFL_SCHEDULE = {
    "Miami Dolphins": [
        "at Las Vegas Raiders",
        "vs San Francisco 49ers",
        "at Kansas City Chiefs",
        "vs Minnesota Vikings",
        "at Cincinnati Bengals",
        "Bye",
        "vs New York Jets",
        "at New England Patriots",
        "vs Detroit Lions",
        "at Indianapolis Colts",
        "vs Buffalo Bills",
        "at New York Jets",
        "vs Denver Broncos",
        "at Chicago Bears",
        "vs Green Bay Packers",
        "at Los Angeles Rams",
        "vs New England Patriots",
        "at Buffalo Bills"
    ],
    "Buffalo Bills": [
        "vs Houston Texans",
        "at Detroit Lions",
        "vs Los Angeles Chargers",
        "at New England Patriots",
        "vs New York Jets",
        "Bye",
        "at Kansas City Chiefs",
        "vs Miami Dolphins",
        "at Cincinnati Bengals",
        "vs Dallas Cowboys",
        "at Miami Dolphins",
        "vs New England Patriots",
        "at New York Jets",
        "vs Philadelphia Eagles",
        "at Washington Commanders",
        "vs Los Angeles Rams",
        "at Arizona Cardinals",
        "vs Miami Dolphins"
    ],
    "New York Jets": [
        "vs New England Patriots",
        "at Buffalo Bills",
        "vs Pittsburgh Steelers",
        "at Miami Dolphins",
        "vs Philadelphia Eagles",
        "at Dallas Cowboys",
        "Bye",
        "vs Miami Dolphins",
        "at New England Patriots",
        "vs Cincinnati Bengals",
        "at Los Angeles Rams",
        "vs Buffalo Bills",
        "at Arizona Cardinals",
        "vs Las Vegas Raiders",
        "at Jacksonville Jaguars",
        "vs New York Giants",
        "at Seattle Seahawks",
        "vs New England Patriots"
    ],
    "New England Patriots": [
        "at New York Jets",
        "vs Miami Dolphins",
        "at Las Vegas Raiders",
        "vs Buffalo Bills",
        "at New York Giants",
        "vs Washington Commanders",
        "at Philadelphia Eagles",
        "Bye",
        "vs New York Jets",
        "at Indianapolis Colts",
        "vs Denver Broncos",
        "at Buffalo Bills",
        "vs Arizona Cardinals",
        "at San Francisco 49ers",
        "vs Los Angeles Chargers",
        "at Baltimore Ravens",
        "vs New York Jets",
        "at Miami Dolphins"
    ],
    "Cincinnati Bengals": [
        "vs Baltimore Ravens",
        "at Pittsburgh Steelers",
        "vs Cleveland Browns",
        "at Kansas City Chiefs",
        "vs Miami Dolphins",
        "at Los Angeles Rams",
        "vs Seattle Seahawks",
        "Bye",
        "at Buffalo Bills",
        "vs New York Jets",
        "at Pittsburgh Steelers",
        "vs Cleveland Browns",
        "at Dallas Cowboys",
        "vs New York Giants",
        "at Tennessee Titans",
        "vs Baltimore Ravens",
        "at Cleveland Browns",
        "vs Pittsburgh Steelers"
    ],
    "Pittsburgh Steelers": [
        "at Cleveland Browns",
        "vs Cincinnati Bengals",
        "at New York Jets",
        "vs Baltimore Ravens",
        "at Indianapolis Colts",
        "vs Dallas Cowboys",
        "Bye",
        "at Green Bay Packers",
        "vs Chicago Bears",
        "at Baltimore Ravens",
        "vs Cincinnati Bengals",
        "at Cleveland Browns",
        "vs Los Angeles Chargers",
        "at Philadelphia Eagles",
        "vs Las Vegas Raiders",
        "at Kansas City Chiefs",
        "vs Cleveland Browns",
        "at Cincinnati Bengals"
    ],
    "Cleveland Browns": [
        "vs Pittsburgh Steelers",
        "at Baltimore Ravens",
        "at Cincinnati Bengals",
        "vs Indianapolis Colts",
        "at Washington Commanders",
        "vs New York Giants",
        "Bye",
        "at Los Angeles Chargers",
        "vs Kansas City Chiefs",
        "at Denver Broncos",
        "vs Pittsburgh Steelers",
        "at Cincinnati Bengals",
        "vs Baltimore Ravens",
        "at Chicago Bears",
        "vs Minnesota Vikings",
        "at Las Vegas Raiders",
        "vs Cincinnati Bengals",
        "at Pittsburgh Steelers"
    ],
    "Baltimore Ravens": [
        "at Cincinnati Bengals",
        "vs Cleveland Browns",
        "at Kansas City Chiefs",
        "at Pittsburgh Steelers",
        "vs Los Angeles Rams",
        "vs Seattle Seahawks",
        "Bye",
        "at Los Angeles Chargers",
        "vs Denver Broncos",
        "vs Pittsburgh Steelers",
        "at Cleveland Browns",
        "vs Indianapolis Colts",
        "at Green Bay Packers",
        "vs Minnesota Vikings",
        "at Chicago Bears",
        "vs Cincinnati Bengals",
        "at Pittsburgh Steelers",
        "vs Cleveland Browns"
    ],
    "Indianapolis Colts": [
        "vs Houston Texans",
        "at Tennessee Titans",
        "vs Jacksonville Jaguars",
        "at Cleveland Browns",
        "vs Pittsburgh Steelers",
        "at Miami Dolphins",
        "Bye",
        "vs Tennessee Titans",
        "at Houston Texans",
        "vs New England Patriots",
        "at Jacksonville Jaguars",
        "at Baltimore Ravens",
        "vs Atlanta Falcons",
        "at Carolina Panthers",
        "vs Tampa Bay Buccaneers",
        "at New Orleans Saints",
        "vs Houston Texans",
        "at Tennessee Titans"
    ],
    "Houston Texans": [
        "at Indianapolis Colts",
        "vs Tennessee Titans",
        "at Jacksonville Jaguars",
        "vs Dallas Cowboys",
        "at New York Giants",
        "Bye",
        "vs Indianapolis Colts",
        "at Tennessee Titans",
        "vs Jacksonville Jaguars",
        "at Green Bay Packers",
        "vs Minnesota Vikings",
        "at Chicago Bears",
        "vs Detroit Lions",
        "at Kansas City Chiefs",
        "vs Los Angeles Chargers",
        "at Las Vegas Raiders",
        "vs Indianapolis Colts",
        "at Tennessee Titans"
    ],
    "Tennessee Titans": [
        "vs Jacksonville Jaguars",
        "vs Indianapolis Colts",
        "at Houston Texans",
        "Bye",
        "vs Miami Dolphins",
        "at New England Patriots",
        "vs Cincinnati Bengals",
        "at Indianapolis Colts",
        "vs Houston Texans",
        "at Jacksonville Jaguars",
        "vs Los Angeles Chargers",
        "at Denver Broncos",
        "vs Kansas City Chiefs",
        "at Las Vegas Raiders",
        "vs Cincinnati Bengals",
        "at Buffalo Bills",
        "vs Jacksonville Jaguars",
        "at Indianapolis Colts"
    ],
    "Jacksonville Jaguars": [
        "at Tennessee Titans",
        "vs Houston Texans",
        "at Indianapolis Colts",
        "vs Atlanta Falcons",
        "at Carolina Panthers",
        "Bye",
        "vs Tampa Bay Buccaneers",
        "at New Orleans Saints",
        "vs Houston Texans",
        "vs Tennessee Titans",
        "at Indianapolis Colts",
        "vs Kansas City Chiefs",
        "at Las Vegas Raiders",
        "vs Los Angeles Chargers",
        "at Denver Broncos",
        "vs New York Jets",
        "at Tennessee Titans",
        "vs Houston Texans"
    ],
    "Los Angeles Chargers": [
        "vs Kansas City Chiefs",
        "at Las Vegas Raiders",
        "at Buffalo Bills",
        "vs Denver Broncos",
        "Bye",
        "vs Miami Dolphins",
        "at New England Patriots",
        "vs Baltimore Ravens",
        "at Cincinnati Bengals",
        "vs Cleveland Browns",
        "at Tennessee Titans",
        "vs Las Vegas Raiders",
        "at Pittsburgh Steelers",
        "vs Denver Broncos",
        "at Houston Texans",
        "vs Kansas City Chiefs",
        "at Dallas Cowboys",
        "vs Denver Broncos"
    ],
    "Kansas City Chiefs": [
        "at Los Angeles Chargers",
        "vs Miami Dolphins",
        "vs Baltimore Ravens",
        "vs Cincinnati Bengals",
        "at Las Vegas Raiders",
        "vs Denver Broncos",
        "Bye",
        "vs Buffalo Bills",
        "at Cleveland Browns",
        "vs Los Angeles Chargers",
        "at Denver Broncos",
        "at Jacksonville Jaguars",
        "vs Tennessee Titans",
        "vs Houston Texans",
        "at Las Vegas Raiders",
        "vs Pittsburgh Steelers",
        "at Los Angeles Chargers",
        "vs Denver Broncos"
    ],
    "Las Vegas Raiders": [
        "vs Miami Dolphins",
        "vs Los Angeles Chargers",
        "vs New England Patriots",
        "at Denver Broncos",
        "vs Kansas City Chiefs",
        "at Los Angeles Rams",
        "Bye",
        "vs Denver Broncos",
        "at Kansas City Chiefs",
        "vs Los Angeles Chargers",
        "at New York Jets",
        "at Jacksonville Jaguars",
        "vs Tennessee Titans",
        "vs Houston Texans",
        "at Kansas City Chiefs",
        "vs Cleveland Browns",
        "at Denver Broncos",
        "vs Los Angeles Chargers"
    ],
    "Denver Broncos": [
        "at Kansas City Chiefs",
        "vs Las Vegas Raiders",
        "at Los Angeles Chargers",
        "vs Las Vegas Raiders",
        "at Miami Dolphins",
        "at Kansas City Chiefs",
        "Bye",
        "at Las Vegas Raiders",
        "vs Cleveland Browns",
        "vs Kansas City Chiefs",
        "vs Los Angeles Chargers",
        "vs Tennessee Titans",
        "at New England Patriots",
        "at Los Angeles Chargers",
        "vs Jacksonville Jaguars",
        "at Cincinnati Bengals",
        "vs Las Vegas Raiders",
        "at Kansas City Chiefs"
    ],
    "New York Giants": [
        "vs Washington Commanders",
        "at Philadelphia Eagles",
        "vs Dallas Cowboys",
        "at New England Patriots",
        "vs Houston Texans",
        "at Cleveland Browns",
        "Bye",
        "vs Philadelphia Eagles",
        "at Washington Commanders",
        "vs Dallas Cowboys",
        "at Cincinnati Bengals",
        "vs New York Jets",
        "at Los Angeles Rams",
        "vs Seattle Seahawks",
        "at Arizona Cardinals",
        "vs San Francisco 49ers",
        "at Washington Commanders",
        "vs Philadelphia Eagles"
    ],
    "Washington Commanders": [
        "at New York Giants",
        "vs Philadelphia Eagles",
        "at Dallas Cowboys",
        "vs New England Patriots",
        "vs Cleveland Browns",
        "at New York Giants",
        "Bye",
        "vs Dallas Cowboys",
        "at Philadelphia Eagles",
        "vs New York Giants",
        "at Dallas Cowboys",
        "vs Philadelphia Eagles",
        "at Minnesota Vikings",
        "vs Chicago Bears",
        "at Green Bay Packers",
        "vs Detroit Lions",
        "vs New York Giants",
        "at Dallas Cowboys"
    ],
    "Philadelphia Eagles": [
        "vs New York Giants",
        "at Washington Commanders",
        "vs Dallas Cowboys",
        "vs New England Patriots",
        "at New York Jets",
        "Bye",
        "vs New York Giants",
        "at Washington Commanders",
        "vs Dallas Cowboys",
        "at New York Giants",
        "vs Washington Commanders",
        "at Dallas Cowboys",
        "vs Pittsburgh Steelers",
        "at Los Angeles Rams",
        "vs Seattle Seahawks",
        "at Arizona Cardinals",
        "vs Washington Commanders",
        "at New York Giants"
    ],
    "Dallas Cowboys": [
        "at New York Giants",
        "vs Washington Commanders",
        "at Philadelphia Eagles",
        "vs Houston Texans",
        "at Pittsburgh Steelers",
        "vs New York Giants",
        "Bye",
        "at Washington Commanders",
        "vs Philadelphia Eagles",
        "at New York Giants",
        "vs Washington Commanders",
        "at Philadelphia Eagles",
        "vs Cincinnati Bengals",
        "at San Francisco 49ers",
        "vs Los Angeles Rams",
        "at Arizona Cardinals",
        "vs Los Angeles Chargers",
        "vs Washington Commanders"
    ],
    "Minnesota Vikings": [
        "vs Chicago Bears",
        "at Green Bay Packers",
        "vs Detroit Lions",
        "at Miami Dolphins",
        "vs Chicago Bears",
        "at Green Bay Packers",
        "Bye",
        "vs Detroit Lions",
        "at Chicago Bears",
        "vs Green Bay Packers",
        "at Houston Texans",
        "at Baltimore Ravens",
        "vs Washington Commanders",
        "at Cleveland Browns",
        "vs Detroit Lions",
        "at Chicago Bears",
        "vs Green Bay Packers",
        "at Detroit Lions"
    ],
    "Chicago Bears": [
        "at Minnesota Vikings",
        "vs Green Bay Packers",
        "at Detroit Lions",
        "vs Miami Dolphins",
        "at Minnesota Vikings",
        "vs Green Bay Packers",
        "Bye",
        "at Detroit Lions",
        "vs Minnesota Vikings",
        "at Pittsburgh Steelers",
        "vs Cleveland Browns",
        "vs Houston Texans",
        "at Green Bay Packers",
        "vs Minnesota Vikings",
        "at Detroit Lions",
        "vs Baltimore Ravens",
        "at Green Bay Packers",
        "vs Minnesota Vikings"
    ],
    "Green Bay Packers": [
        "vs Minnesota Vikings",
        "at Chicago Bears",
        "vs Detroit Lions",
        "at Minnesota Vikings",
        "vs Chicago Bears",
        "at Detroit Lions",
        "Bye",
        "vs Pittsburgh Steelers",
        "at Minnesota Vikings",
        "vs Chicago Bears",
        "at Detroit Lions",
        "vs Baltimore Ravens",
        "at Chicago Bears",
        "vs Washington Commanders",
        "at Minnesota Vikings",
        "vs Chicago Bears",
        "at Detroit Lions",
        "vs Minnesota Vikings"
    ],
    "Detroit Lions": [
        "at Minnesota Vikings",
        "vs Buffalo Bills",
        "at Chicago Bears",
        "vs Green Bay Packers",
        "at Miami Dolphins",
        "vs Green Bay Packers",
        "Bye",
        "at Minnesota Vikings",
        "vs Chicago Bears",
        "at Green Bay Packers",
        "vs Minnesota Vikings",
        "at Houston Texans",
        "vs Chicago Bears",
        "at Washington Commanders",
        "vs Minnesota Vikings",
        "at Green Bay Packers",
        "vs Chicago Bears",
        "at Minnesota Vikings"
    ],
    "New Orleans Saints": [
        "vs Atlanta Falcons",
        "at Tampa Bay Buccaneers",
        "vs Carolina Panthers",
        "Bye",
        "vs Jacksonville Jaguars",
        "at Indianapolis Colts",
        "vs Tampa Bay Buccaneers",
        "at Atlanta Falcons",
        "vs Carolina Panthers",
        "at Tampa Bay Buccaneers",
        "vs Atlanta Falcons",
        "at Carolina Panthers",
        "vs Indianapolis Colts",
        "at Tampa Bay Buccaneers",
        "vs Atlanta Falcons",
        "at Carolina Panthers",
        "vs Tampa Bay Buccaneers",
        "at Atlanta Falcons"
    ],
    "Tampa Bay Buccaneers": [
        "at New Orleans Saints",
        "vs Atlanta Falcons",
        "at Carolina Panthers",
        "Bye",
        "vs Jacksonville Jaguars",
        "at Indianapolis Colts",
        "vs New Orleans Saints",
        "at Atlanta Falcons",
        "vs Carolina Panthers",
        "at New Orleans Saints",
        "vs Atlanta Falcons",
        "at Carolina Panthers",
        "vs New Orleans Saints",
        "at Atlanta Falcons",
        "vs Carolina Panthers",
        "at Indianapolis Colts",
        "vs New Orleans Saints",
        "at Atlanta Falcons"
    ],
    "Atlanta Falcons": [
        "at New Orleans Saints",
        "vs Tampa Bay Buccaneers",
        "at Carolina Panthers",
        "Bye",
        "vs Jacksonville Jaguars",
        "at Indianapolis Colts",
        "vs New Orleans Saints",
        "at Tampa Bay Buccaneers",
        "vs Carolina Panthers",
        "at New Orleans Saints",
        "vs Tampa Bay Buccaneers",
        "at Carolina Panthers",
        "vs New Orleans Saints",
        "at Tampa Bay Buccaneers",
        "vs Carolina Panthers",
        "at New Orleans Saints",
        "vs Tampa Bay Buccaneers",
        "at Carolina Panthers"
    ],
    "Carolina Panthers": [
        "vs New Orleans Saints",
        "at Tampa Bay Buccaneers",
        "vs Atlanta Falcons",
        "Bye",
        "vs Jacksonville Jaguars",
        "at Indianapolis Colts",
        "vs New Orleans Saints",
        "at Tampa Bay Buccaneers",
        "vs Atlanta Falcons",
        "at New Orleans Saints",
        "vs Tampa Bay Buccaneers",
        "at Atlanta Falcons",
        "vs New Orleans Saints",
        "at Tampa Bay Buccaneers",
        "vs Atlanta Falcons",
        "at New Orleans Saints",
        "vs Tampa Bay Buccaneers",
        "at Atlanta Falcons"
    ],
    "Los Angeles Rams": [
        "vs Seattle Seahawks",
        "at Arizona Cardinals",
        "vs San Francisco 49ers",
        "at Cincinnati Bengals",
        "at Baltimore Ravens",
        "vs Las Vegas Raiders",
        "Bye",
        "vs Arizona Cardinals",
        "at Seattle Seahawks",
        "vs San Francisco 49ers",
        "at New York Jets",
        "vs New York Giants",
        "at Buffalo Bills",
        "vs Philadelphia Eagles",
        "at Dallas Cowboys",
        "vs Miami Dolphins",
        "at San Francisco 49ers",
        "vs Seattle Seahawks"
    ],
    "Seattle Seahawks": [
        "at Los Angeles Rams",
        "vs Arizona Cardinals",
        "at San Francisco 49ers",
        "Bye",
        "vs Cincinnati Bengals",
        "at Baltimore Ravens",
        "vs Los Angeles Rams",
        "at Arizona Cardinals",
        "vs San Francisco 49ers",
        "at Los Angeles Rams",
        "vs Arizona Cardinals",
        "at San Francisco 49ers",
        "vs New York Giants",
        "at Philadelphia Eagles",
        "vs New York Jets",
        "at Los Angeles Rams",
        "vs San Francisco 49ers",
        "at Arizona Cardinals"
    ],
    "Arizona Cardinals": [
        "vs Seattle Seahawks",
        "vs Los Angeles Rams",
        "at San Francisco 49ers",
        "Bye",
        "at Seattle Seahawks",
        "vs Los Angeles Rams",
        "at San Francisco 49ers",
        "vs Seattle Seahawks",
        "at Los Angeles Rams",
        "vs San Francisco 49ers",
        "at Seattle Seahawks",
        "vs New England Patriots",
        "at New York Jets",
        "vs New York Giants",
        "at Dallas Cowboys",
        "vs Philadelphia Eagles",
        "at Buffalo Bills",
        "vs Seattle Seahawks"
    ],
    "San Francisco 49ers": [
        "vs Seattle Seahawks",
        "at Los Angeles Rams",
        "vs Arizona Cardinals",
        "Bye",
        "at Seattle Seahawks",
        "vs Los Angeles Rams",
        "at Arizona Cardinals",
        "vs Seattle Seahawks",
        "at Los Angeles Rams",
        "vs Arizona Cardinals",
        "at Seattle Seahawks",
        "vs New England Patriots",
        "at New York Jets",
        "vs Dallas Cowboys",
        "at Los Angeles Rams",
        "vs New York Giants",
        "at Seattle Seahawks",
        "vs Arizona Cardinals"
    ]
}