# 2026 NFL Schedule Data

NFL_SCHEDULE = {
    "Buffalo Bills": [
        "at Houston Texans",
        "vs. Detroit Lions",
        "vs. Los Angeles Chargers",
        "vs. New England Patriots",
        "at Los Angeles Rams",
        "at Las Vegas Raiders",
        "BYE",
        "vs. Baltimore Ravens",
        "at Minnesota Vikings",
        "at New York Jets",
        "vs. Miami Dolphins",
        "vs. Kansas City Chiefs",
        "at New England Patriots",
        "at Green Bay Packers",
        "vs. Chicago Bears",
        "at Denver Broncos",
        "at Miami Dolphins",
        "vs. New York Jets"
    ],
    "Miami Dolphins": [
        "at Las Vegas Raiders",
        "at San Francisco 49ers",
        "vs. Kansas City Chiefs",
        "at Minnesota Vikings",
        "vs. Cincinnati Bengals",
        "BYE",
        "at New York Jets",
        "vs. New England Patriots",
        "vs. Detroit Lions",
        "at Indianapolis Colts",
        "at Buffalo Bills",
        "vs. New York Jets",
        "at Denver Broncos",
        "vs. Chicago Bears",
        "at Green Bay Packers",
        "vs. Los Angeles Chargers",
        "vs. Buffalo Bills",
        "at New England Patriots"
    ],
    "New England Patriots": [
        "at Seattle Seahawks",
        "vs. Pittsburgh Steelers",
        "at Jacksonville Jaguars",
        "at Buffalo Bills",
        "vs. Las Vegas Raiders",
        "vs. New York Jets",
        "at Chicago Bears",
        "vs. Miami Dolphins",
        "vs. Green Bay Packers",
        "vs. Detroit Lions",
        "BYE",
        "vs. Los Angeles Chargers",
        "vs. Buffalo Bills",
        "vs. Minnesota Vikings",
        "at Kansas City Chiefs",
        "at New York Jets",
        "vs. Denver Broncos",
        "vs. Miami Dolphins"
    ],
    "New York Jets": [
        "at Tennessee Titans",
        "vs. Green Bay Packers",
        "at Detroit Lions",
        "at Chicago Bears",
        "vs. Cleveland Browns",
        "at New England Patriots",
        "vs. Miami Dolphins",
        "vs. Las Vegas Raiders",
        "at Kansas City Chiefs",
        "vs. Buffalo Bills",
        "at Los Angeles Rams",
        "at Miami Dolphins",
        "BYE",
        "vs. Denver Broncos",
        "at Arizona Cardinals",
        "vs. New England Patriots",
        "vs. Minnesota Vikings",
        "at Buffalo Bills"
    ],
    "Baltimore Ravens": [
        "at Indianapolis Colts",
        "vs. New Orleans Saints",
        "at Dallas Cowboys",
        "vs. Tennessee Titans",
        "at Atlanta Falcons",
        "at Cleveland Browns",
        "vs. Cincinnati Bengals",
        "at Buffalo Bills",
        "vs. Jacksonville Jaguars",
        "vs. Los Angeles Chargers",
        "at Carolina Panthers",
        "at Houston Texans",
        "BYE",
        "vs. Tampa Bay Buccaneers",
        "at Pittsburgh Steelers",
        "vs. Cleveland Browns",
        "at Cincinnati Bengals",
        "vs. Pittsburgh Steelers"
    ],
    "Cincinnati Bengals": [
        "vs. Tampa Bay Buccaneers",
        "at Houston Texans",
        "at Pittsburgh Steelers",
        "vs. Jacksonville Jaguars",
        "at Miami Dolphins",
        "BYE",
        "at Baltimore Ravens",
        "vs. Tennessee Titans",
        "vs. Atlanta Falcons",
        "vs. Pittsburgh Steelers",
        "at Washington Commanders",
        "vs. New Orleans Saints",
        "at Cleveland Browns",
        "vs. Kansas City Chiefs",
        "at Carolina Panthers",
        "at Indianapolis Colts",
        "vs. Baltimore Ravens",
        "vs. Cleveland Browns"
    ],
    "Cleveland Browns": [
        "at Jacksonville Jaguars",
        "at Tampa Bay Buccaneers",
        "vs. Carolina Panthers",
        "vs. Pittsburgh Steelers",
        "at New York Jets",
        "vs. Baltimore Ravens",
        "at Tennessee Titans",
        "at Pittsburgh Steelers",
        "at New Orleans Saints",
        "vs. Houston Texans",
        "BYE",
        "vs. Las Vegas Raiders",
        "vs. Cincinnati Bengals",
        "vs. Atlanta Falcons",
        "at New York Giants",
        "at Baltimore Ravens",
        "vs. Indianapolis Colts",
        "at Cincinnati Bengals"
    ],
    "Pittsburgh Steelers": [
        "vs. Atlanta Falcons",
        "at New England Patriots",
        "vs. Cincinnati Bengals",
        "at Cleveland Browns",
        "vs. Indianapolis Colts",
        "at Tampa Bay Buccaneers",
        "vs. New Orleans Saints",
        "vs. Cleveland Browns",
        "BYE",
        "at Cincinnati Bengals",
        "at Philadelphia Eagles",
        "vs. Denver Broncos",
        "vs. Houston Texans",
        "at Jacksonville Jaguars",
        "vs. Baltimore Ravens",
        "vs. Carolina Panthers",
        "at Tennessee Titans",
        "at Baltimore Ravens"
    ],
    "Houston Texans": [
        "vs. Buffalo Bills",
        "vs. Cincinnati Bengals",
        "at Indianapolis Colts",
        "vs. Dallas Cowboys",
        "at Tennessee Titans",
        "at Jacksonville Jaguars",
        "vs. New York Giants",
        "BYE",
        "at Los Angeles Chargers",
        "at Cleveland Browns",
        "vs. Indianapolis Colts",
        "vs. Baltimore Ravens",
        "at Pittsburgh Steelers",
        "at Washington Commanders",
        "vs. Jacksonville Jaguars",
        "at Philadelphia Eagles",
        "at Green Bay Packers",
        "vs. Tennessee Titans"
    ],
    "Indianapolis Colts": [
        "vs. Baltimore Ravens",
        "at Kansas City Chiefs",
        "vs. Houston Texans",
        "at Washington Commanders",
        "at Pittsburgh Steelers",
        "vs. Tennessee Titans",
        "at Minnesota Vikings",
        "at Jacksonville Jaguars",
        "vs. Dallas Cowboys",
        "vs. Miami Dolphins",
        "at Houston Texans",
        "vs. New York Giants",
        "BYE",
        "at Philadelphia Eagles",
        "at Tennessee Titans",
        "vs. Cincinnati Bengals",
        "at Cleveland Browns",
        "vs. Jacksonville Jaguars"
    ],
    "Jacksonville Jaguars": [
        "vs. Cleveland Browns",
        "at Denver Broncos",
        "vs. New England Patriots",
        "at Cincinnati Bengals",
        "vs. Philadelphia Eagles",
        "vs. Houston Texans",
        "BYE",
        "vs. Indianapolis Colts",
        "at Baltimore Ravens",
        "at Tennessee Titans",
        "at New York Giants",
        "vs. Tennessee Titans",
        "at Chicago Bears",
        "vs. Pittsburgh Steelers",
        "at Houston Texans",
        "at Dallas Cowboys",
        "vs. Washington Commanders",
        "at Indianapolis Colts"
    ],
    "Tennessee Titans": [
        "vs. New York Jets",
        "vs. Philadelphia Eagles",
        "at New York Giants",
        "at Baltimore Ravens",
        "vs. Houston Texans",
        "at Indianapolis Colts",
        "vs. Cleveland Browns",
        "at Cincinnati Bengals",
        "BYE",
        "vs. Jacksonville Jaguars",
        "at Dallas Cowboys",
        "at Jacksonville Jaguars",
        "vs. Washington Commanders",
        "at Detroit Lions",
        "vs. Indianapolis Colts",
        "at Las Vegas Raiders",
        "vs. Pittsburgh Steelers",
        "at Houston Texans"
    ],
    "Denver Broncos": [
        "at Kansas City Chiefs",
        "vs. Jacksonville Jaguars",
        "vs. Los Angeles Rams",
        "at San Francisco 49ers",
        "at Los Angeles Chargers",
        "vs. Seattle Seahawks",
        "at Arizona Cardinals",
        "vs. Kansas City Chiefs",
        "at Carolina Panthers",
        "BYE",
        "vs. Las Vegas Raiders",
        "at Pittsburgh Steelers",
        "vs. Miami Dolphins",
        "at New York Jets",
        "at Las Vegas Raiders",
        "vs. Buffalo Bills",
        "at New England Patriots",
        "vs. Los Angeles Chargers"
    ],
    "Kansas City Chiefs": [
        "vs. Denver Broncos",
        "vs. Indianapolis Colts",
        "at Miami Dolphins",
        "at Las Vegas Raiders",
        "BYE",
        "vs. Los Angeles Chargers",
        "at Seattle Seahawks",
        "at Denver Broncos",
        "vs. New York Jets",
        "at Atlanta Falcons",
        "vs. Arizona Cardinals",
        "at Buffalo Bills",
        "at Los Angeles Rams",
        "at Cincinnati Bengals",
        "vs. New England Patriots",
        "vs. San Francisco 49ers",
        "at Los Angeles Chargers",
        "vs. Las Vegas Raiders"
    ],
    "Las Vegas Raiders": [
        "vs. Miami Dolphins",
        "at Los Angeles Chargers",
        "at New Orleans Saints",
        "vs. Kansas City Chiefs",
        "at New England Patriots",
        "vs. Buffalo Bills",
        "vs. Los Angeles Rams",
        "at New York Jets",
        "at San Francisco 49ers",
        "vs. Seattle Seahawks",
        "at Denver Broncos",
        "at Cleveland Browns",
        "BYE",
        "vs. Los Angeles Chargers",
        "vs. Denver Broncos",
        "vs. Tennessee Titans",
        "at Arizona Cardinals",
        "at Kansas City Chiefs"
    ],
    "Los Angeles Chargers": [
        "vs. Arizona Cardinals",
        "vs. Las Vegas Raiders",
        "at Buffalo Bills",
        "at Seattle Seahawks",
        "vs. Denver Broncos",
        "at Kansas City Chiefs",
        "BYE",
        "at Los Angeles Rams",
        "vs. Houston Texans",
        "at Baltimore Ravens",
        "vs. New York Jets",
        "vs. New England Patriots",
        "at Tampa Bay Buccaneers",
        "at Las Vegas Raiders",
        "vs. San Francisco 49ers",
        "at Miami Dolphins",
        "vs. Kansas City Chiefs",
        "vs. Denver Broncos"
    ],
    "Dallas Cowboys": [
        "at New York Giants",
        "vs. Washington Commanders",
        "vs. Baltimore Ravens",
        "at Houston Texans",
        "vs. Tampa Bay Buccaneers",
        "at Green Bay Packers",
        "at Philadelphia Eagles",
        "vs. Arizona Cardinals",
        "at Indianapolis Colts",
        "vs. San Francisco 49ers",
        "vs. Tennessee Titans",
        "vs. Philadelphia Eagles",
        "at Seattle Seahawks",
        "BYE",
        "at Los Angeles Rams",
        "vs. Jacksonville Jaguars",
        "vs. New York Giants",
        "at Washington Commanders"
    ],
    "New York Giants": [
        "vs. Dallas Cowboys",
        "at Los Angeles Rams",
        "vs. Tennessee Titans",
        "vs. Arizona Cardinals",
        "at Washington Commanders",
        "vs. New Orleans Saints",
        "at Houston Texans",
        "BYE",
        "at Philadelphia Eagles",
        "vs. Washington Commanders",
        "vs. Jacksonville Jaguars",
        "at Indianapolis Colts",
        "vs. San Francisco 49ers",
        "at Seattle Seahawks",
        "vs. Cleveland Browns",
        "at Detroit Lions",
        "at Dallas Cowboys",
        "vs. Philadelphia Eagles"
    ],
    "Philadelphia Eagles": [
        "vs. Washington Commanders",
        "at Tennessee Titans",
        "at Chicago Bears",
        "vs. Los Angeles Rams",
        "at Jacksonville Jaguars",
        "vs. Carolina Panthers",
        "vs. Dallas Cowboys",
        "at Washington Commanders",
        "vs. New York Giants",
        "BYE",
        "vs. Pittsburgh Steelers",
        "at Dallas Cowboys",
        "at Arizona Cardinals",
        "vs. Indianapolis Colts",
        "vs. Seattle Seahawks",
        "vs. Houston Texans",
        "at San Francisco 49ers",
        "at New York Giants"
    ],
    "Washington Commanders": [
        "at Philadelphia Eagles",
        "at Dallas Cowboys",
        "vs. Seattle Seahawks",
        "vs. Indianapolis Colts",
        "vs. New York Giants",
        "at San Francisco 49ers",
        "BYE",
        "vs. Philadelphia Eagles",
        "vs. Los Angeles Rams",
        "at New York Giants",
        "vs. Cincinnati Bengals",
        "at Arizona Cardinals",
        "at Tennessee Titans",
        "vs. Houston Texans",
        "vs. Atlanta Falcons",
        "at Minnesota Vikings",
        "at Jacksonville Jaguars",
        "vs. Dallas Cowboys"
    ],
    "Chicago Bears": [
        "at Carolina Panthers",
        "vs. Minnesota Vikings",
        "vs. Philadelphia Eagles",
        "vs. New York Jets",
        "at Green Bay Packers",
        "at Atlanta Falcons",
        "vs. New England Patriots",
        "at Seattle Seahawks",
        "vs. Tampa Bay Buccaneers",
        "BYE",
        "vs. New Orleans Saints",
        "at Detroit Lions",
        "vs. Jacksonville Jaguars",
        "at Miami Dolphins",
        "at Buffalo Bills",
        "vs. Green Bay Packers",
        "vs. Detroit Lions",
        "at Minnesota Vikings"
    ],
    "Detroit Lions": [
        "vs. New Orleans Saints",
        "at Buffalo Bills",
        "vs. New York Jets",
        "at Carolina Panthers",
        "at Arizona Cardinals",
        "BYE",
        "vs. Green Bay Packers",
        "vs. Minnesota Vikings",
        "at Miami Dolphins",
        "vs. New England Patriots",
        "vs. Tampa Bay Buccaneers",
        "vs. Chicago Bears",
        "at Atlanta Falcons",
        "vs. Tennessee Titans",
        "at Minnesota Vikings",
        "vs. New York Giants",
        "at Chicago Bears",
        "at Green Bay Packers"
    ],
    "Green Bay Packers": [
        "at Minnesota Vikings",
        "at New York Jets",
        "vs. Atlanta Falcons",
        "at Tampa Bay Buccaneers",
        "vs. Chicago Bears",
        "vs. Dallas Cowboys",
        "at Detroit Lions",
        "vs. Carolina Panthers",
        "at New England Patriots",
        "vs. Minnesota Vikings",
        "BYE",
        "at Los Angeles Rams",
        "at New Orleans Saints",
        "vs. Buffalo Bills",
        "vs. Miami Dolphins",
        "at Chicago Bears",
        "vs. Houston Texans",
        "vs. Detroit Lions"
    ],
    "Minnesota Vikings": [
        "vs. Green Bay Packers",
        "at Chicago Bears",
        "at Tampa Bay Buccaneers",
        "vs. Miami Dolphins",
        "at New Orleans Saints",
        "BYE",
        "vs. Indianapolis Colts",
        "at Detroit Lions",
        "vs. Buffalo Bills",
        "at Green Bay Packers",
        "vs. San Francisco 49ers",
        "vs. Atlanta Falcons",
        "vs. Carolina Panthers",
        "at New England Patriots",
        "vs. Detroit Lions",
        "vs. Washington Commanders",
        "at New York Jets",
        "vs. Chicago Bears"
    ],
    "Atlanta Falcons": [
        "at Pittsburgh Steelers",
        "vs. Carolina Panthers",
        "at Green Bay Packers",
        "at New Orleans Saints",
        "vs. Baltimore Ravens",
        "vs. Chicago Bears",
        "vs. San Francisco 49ers",
        "at Tampa Bay Buccaneers",
        "vs. Cincinnati Bengals",
        "vs. Kansas City Chiefs",
        "BYE",
        "at Minnesota Vikings",
        "vs. Detroit Lions",
        "at Cleveland Browns",
        "at Washington Commanders",
        "vs. Tampa Bay Buccaneers",
        "vs. New Orleans Saints",
        "at Carolina Panthers"
    ],
    "Carolina Panthers": [
        "vs. Chicago Bears",
        "at Atlanta Falcons",
        "at Cleveland Browns",
        "vs. Detroit Lions",
        "BYE",
        "at Philadelphia Eagles",
        "vs. Tampa Bay Buccaneers",
        "at Green Bay Packers",
        "vs. Denver Broncos",
        "at New Orleans Saints",
        "vs. Baltimore Ravens",
        "at Tampa Bay Buccaneers",
        "at Minnesota Vikings",
        "vs. New Orleans Saints",
        "vs. Cincinnati Bengals",
        "at Pittsburgh Steelers",
        "vs. Seattle Seahawks",
        "vs. Atlanta Falcons"
    ],
    "New Orleans Saints": [
        "at Detroit Lions",
        "at Baltimore Ravens",
        "vs. Las Vegas Raiders",
        "vs. Atlanta Falcons",
        "vs. Minnesota Vikings",
        "at New York Giants",
        "at Pittsburgh Steelers",
        "BYE",
        "vs. Cleveland Browns",
        "vs. Carolina Panthers",
        "at Chicago Bears",
        "at Cincinnati Bengals",
        "vs. Green Bay Packers",
        "at Carolina Panthers",
        "at Tampa Bay Buccaneers",
        "vs. Arizona Cardinals",
        "at Atlanta Falcons",
        "vs. Tampa Bay Buccaneers"
    ],
    "Tampa Bay Buccaneers": [
        "at Cincinnati Bengals",
        "vs. Cleveland Browns",
        "vs. Minnesota Vikings",
        "vs. Green Bay Packers",
        "at Dallas Cowboys",
        "vs. Pittsburgh Steelers",
        "at Carolina Panthers",
        "vs. Atlanta Falcons",
        "at Chicago Bears",
        "BYE",
        "at Detroit Lions",
        "vs. Carolina Panthers",
        "vs. Los Angeles Chargers",
        "at Baltimore Ravens",
        "vs. New Orleans Saints",
        "at Atlanta Falcons",
        "vs. Los Angeles Rams",
        "at New Orleans Saints"
    ],
    "Arizona Cardinals": [
        "at Los Angeles Chargers",
        "vs. Seattle Seahawks",
        "at San Francisco 49ers",
        "at New York Giants",
        "vs. Detroit Lions",
        "at Los Angeles Rams",
        "vs. Denver Broncos",
        "at Dallas Cowboys",
        "at Seattle Seahawks",
        "vs. Los Angeles Rams",
        "at Kansas City Chiefs",
        "vs. Washington Commanders",
        "vs. Philadelphia Eagles",
        "BYE",
        "vs. New York Jets",
        "at New Orleans Saints",
        "vs. Las Vegas Raiders",
        "vs. San Francisco 49ers"
    ],
    "Los Angeles Rams": [
        "vs. San Francisco 49ers",
        "vs. New York Giants",
        "at Denver Broncos",
        "at Philadelphia Eagles",
        "vs. Buffalo Bills",
        "vs. Arizona Cardinals",
        "at Las Vegas Raiders",
        "vs. Los Angeles Chargers",
        "at Washington Commanders",
        "at Arizona Cardinals",
        "BYE",
        "vs. Green Bay Packers",
        "vs. Kansas City Chiefs",
        "at San Francisco 49ers",
        "vs. Dallas Cowboys",
        "at Seattle Seahawks",
        "at Tampa Bay Buccaneers",
        "vs. Seattle Seahawks"
    ],
    "San Francisco 49ers": [
        "at Los Angeles Rams",
        "vs. Miami Dolphins",
        "vs. Arizona Cardinals",
        "vs. Denver Broncos",
        "at Seattle Seahawks",
        "vs. Washington Commanders",
        "at Atlanta Falcons",
        "BYE",
        "vs. Las Vegas Raiders",
        "at Dallas Cowboys",
        "vs. Minnesota Vikings",
        "vs. Seattle Seahawks",
        "at New York Giants",
        "vs. Los Angeles Rams",
        "at Los Angeles Chargers",
        "at Kansas City Chiefs",
        "vs. Philadelphia Eagles",
        "at Arizona Cardinals"
    ],
    "Seattle Seahawks": [
        "vs. New England Patriots",
        "at Arizona Cardinals",
        "at Washington Commanders",
        "vs. Los Angeles Chargers",
        "vs. San Francisco 49ers",
        "at Denver Broncos",
        "vs. Kansas City Chiefs",
        "vs. Chicago Bears",
        "vs. Arizona Cardinals",
        "at Las Vegas Raiders",
        "BYE",
        "at San Francisco 49ers",
        "vs. Dallas Cowboys",
        "vs. New York Giants",
        "at Philadelphia Eagles",
        "vs. Los Angeles Rams",
        "at Carolina Panthers",
        "at Los Angeles Rams"
    ]
}
